name: Create release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # fetch all history for sentry propose-version step
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build with source map
        run: GENERATE_SOURCEMAP=true yarn build
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }} # Ref: https://github.com/marketplace/actions/sentry-release#prerequisites
          SENTRY_ORG: <YOUR_SENTRY_ORG>
          SENTRY_PROJECT: <YOUR_SENTRY_PROJECT>
        with:
          environment: production # e.g. develop, staging, production
          ignore_empty: true
          sourcemaps: ./build/static/js/
          url_prefix: ~/static/js
